[package]
name = "binary-command-editor"
version = "0.1.0"
description = "A Tauri App for editing binary commands"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "dialog-confirm", "dialog-message", "dialog-ask", "fs-exists", "shell-open", "path-all", "dialog-open", "fs-read-file", "dialog-save", "fs-write-file"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
