// Danh sách 47 lệnh base của hệ thống
export const BASE_COMMANDS = [
    'Bull',
    '8etExpTimes',
    'SetExpTimes',
    'GetLootTimes',
    'SetLootTimes',
    'GetOnline',
    'SetOnlineMax',
    'ClearPassword',
    'DelChar',
    'GetAccCharList',
    'GetChar',
    'GetLineOnline',
    'SetLineOnlineMax',
    'OpenIPList',
    'CloseIPList',
    'FriendClose',
    'ForceClose(to Manager)',
    'GetHighestOnline',
    'GetChildLst(REM)',
    'GetChildStatus(REM)',
    'SetChar',
    'GetCharItem',
    'SaveCharItem',
    'ChangeGuildName',
    'AddForbidTalk',
    'AddForbidLogin',
    'DelForbidTalk',
    'DelForbidLogin',
    'GetServerStatus',
    'GameServerStart',
    'GetAccID',
    'GetCharID',
    'GetProcessLst',
    'MailItemToPlayer',
    'GSClose',
    'GetLineOnlineMax',
    'DisbandGuild',
    'GetCharPet',
    'SaveCharPet',
    'ExchangeName',
    'ResetAttrib',
    'GetServerVersion',
    'CloseProcess',
    'GetCharData',
    'SaveCharData',
    'ForceClose(to Guarder)'
] as const;

export type BaseCommand = typeof BASE_COMMANDS[number];
